language: cpp
compiler:
    - gcc
    - clang
before_install:
    - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
    - "sudo apt-get update -qq"
    - "sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev cmake gcc-4.9 clang"
    - "gcc --version"

    
script: mkdir build && cd build && cmake ../ && make -j && ../runTests