language: cpp
compiler:
    - gcc
    - clang
before_install:
    sudo apt-get update -qq &&
    sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev cmake g++ clang

    
script: mkdir build && cd build && cmake ../ && make -j